//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/CircleGesture/GestureControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GestureControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GestureControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GestureControls"",
    ""maps"": [
        {
            ""name"": ""DefaultActionMap"",
            ""id"": ""2b5443ee-dc0a-418c-8f1e-9c53f5d368cc"",
            ""actions"": [
                {
                    ""name"": ""CircleAction"",
                    ""type"": ""Value"",
                    ""id"": ""e7bf42c3-2825-4038-a1f8-5a7ac11ebf36"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""314b4605-250d-4135-8de2-23417ddb4104"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": ""Circle(duration=1,pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CircleAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DefaultActionMap
        m_DefaultActionMap = asset.FindActionMap("DefaultActionMap", throwIfNotFound: true);
        m_DefaultActionMap_CircleAction = m_DefaultActionMap.FindAction("CircleAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DefaultActionMap
    private readonly InputActionMap m_DefaultActionMap;
    private IDefaultActionMapActions m_DefaultActionMapActionsCallbackInterface;
    private readonly InputAction m_DefaultActionMap_CircleAction;
    public struct DefaultActionMapActions
    {
        private @GestureControls m_Wrapper;
        public DefaultActionMapActions(@GestureControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CircleAction => m_Wrapper.m_DefaultActionMap_CircleAction;
        public InputActionMap Get() { return m_Wrapper.m_DefaultActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActionMapActions instance)
        {
            if (m_Wrapper.m_DefaultActionMapActionsCallbackInterface != null)
            {
                @CircleAction.started -= m_Wrapper.m_DefaultActionMapActionsCallbackInterface.OnCircleAction;
                @CircleAction.performed -= m_Wrapper.m_DefaultActionMapActionsCallbackInterface.OnCircleAction;
                @CircleAction.canceled -= m_Wrapper.m_DefaultActionMapActionsCallbackInterface.OnCircleAction;
            }
            m_Wrapper.m_DefaultActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CircleAction.started += instance.OnCircleAction;
                @CircleAction.performed += instance.OnCircleAction;
                @CircleAction.canceled += instance.OnCircleAction;
            }
        }
    }
    public DefaultActionMapActions @DefaultActionMap => new DefaultActionMapActions(this);
    public interface IDefaultActionMapActions
    {
        void OnCircleAction(InputAction.CallbackContext context);
    }
}
